### ISSUE TITLE
Add campsite type include/exclude option for provider ReserveCalifornia

### ISSUE THREAD

**Issue by lukelwang** [juftin/camply#251] opened 2023-05-10 03:46 UTC
**Is your feature request related to a problem? Please describe.**
When I searched campsite in Henry Cowell Redwoods SP, it always showed availability. However, when I checked the link as below, I found it was due to one site (Walk-In Only) was always available. 
https://www.reservecalifornia.com/Web/Default.aspx#!park/655/505

**Describe the solution you'd like**
I would like an argument that can specify what kind of campsite to include or exclude. That would be neat.

**Describe alternatives you've considered**
For this use case, I don't have a workaround.

**Additional context**

**Comment by juftin** [comment] 2023-05-10 18:16
This sounds like a good candidate for campsite attribute filtering.

See https://github.com/juftin/camply/issues/86 and https://github.com/juftin/camply/discussions/63

**Comment by juftin** [comment] 2023-06-06 19:46
Closiing as a duplicate of #86

**Closed** 2023-06-06 19:45 UTC
Labels: duplicate

**Comment by Syzygianinfern0** [comment] 2024-06-22 01:23
> When I searched campsite in Henry Cowell Redwoods SP, it always showed availability. However, when I checked the link as below, I found it was due to one site (Walk-In Only) was always available.

Is it possible to do this anyhow right now?

**Comment by Syzygianinfern0** [comment] 2024-06-22 01:23
@juftin

**Comment by Syzygianinfern0** [comment] 2024-06-22 01:29
For now, I've just ended up listing them individually like so

```bash
camply campsites \
    --provider ReserveCalifornia \
    --rec-area 697 \
    --campground 632 \
    --campsite 44185 \
    --campsite 44186 \
    --campsite 44187 \
    --campsite 44188 \
    --campsite 44189 \
    --campsite 44190 \
    --campsite 44191 \
    --campsite 44192 \
    --campsite 44193 \
    --campsite 44194 \
    --campsite 44195 \
    --campsite 44196 \
    --campsite 44197 \
    --campsite 44198 \
    --campsite 44199 \
    --campsite 44200 \
    --campsite 44201 \
    --campsite 44178 \
    --campsite 44179 \
    --campsite 44180 \
    --campsite 44181 \
    --campsite 44182 \
    --campsite 44183 \
    --campsite 44184 \
    --start-date 2024-07-05 \
    --end-date 2024-07-06 \
    --continuous \
    --notify-first-try \
    --polling-interval 5 \
    --notifications telegram
```
